// <auto-generated />
namespace Vidly_2nd_try.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeindataofbirthcustomers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeindataofbirthcustomers));
        
        string IMigrationMetadata.Id
        {
            get { return "202212171709341_changeindataofbirthcustomers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
